trigger:
- main

stages:
  - stage: Build
    jobs:
    - job: Build
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'install -D tailwindcss postcss autoprefixer'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
      - task: Npm@1
        inputs:
          command: 'publish'
          workingDir: './dist'
          publishRegistry: 'useFeed'
          publishFeed: '661d3a93-15e7-460d-9084-8e2d6816f177/db749be6-612b-45a7-a409-20115f87f55a'
